server:
  port: 8080
  servlet:
    context-path: /dnshosts/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ymm_hosts_0617?serverTimezone=GMT%2B8
    username: root
    password: ENC(vEvXhHtMtKmJbsdQtTC4Pg==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      cache: false
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      enabled: true
      exclude: webapp/**
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.dns.dnshosts.mapper: debug
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace
    mysql: debug
  path:
    config: classpath:log4j.properties

#加解密
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: ljk

